In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df2022 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2022.csv', index_col=None, header=0, encoding='cp949')
df2021 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2021.csv', index_col=None, header=0, encoding='cp949')
df2020 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2020.csv', index_col=None, header=0, encoding='cp949')
df2019 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2019.csv', index_col=None, header=0, encoding='cp949')
df2018 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2018.csv', index_col=None, header=0, encoding='cp949')
df2017 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2017.csv', index_col=None, header=0, encoding='cp949')
df2016 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2016.csv', index_col=None, header=0, encoding='cp949')
df2015 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2015.csv', index_col=None, header=0, encoding='cp949')
df2014 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2014.csv', index_col=None, header=0, encoding='cp949')
df2013 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2013.csv', index_col=None, header=0, encoding='cp949')

<ipython-input-2-da2ea29e0ed0>:2: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2021 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2021.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:3: DtypeWarning: Columns (6,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2020 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2020.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:4: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2019 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2019.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:5: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2018 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2018.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:6: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2017 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2017.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:7: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2016 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2016.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:8: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2015 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2015.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:9: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2014 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2014.csv', index_col=None, header=0, encoding='cp949')
<ipython-input-2-da2ea29e0ed0>:10: DtypeWarning: Columns (6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df2013 = pd.read_csv('/content/drive/MyDrive/project2/서울특별시_전월세가_2013.csv', index_col=None, header=0, encoding='cp949')

In [ ]:
df = pd.concat([df2022, df2021, df2020, df2019, df2018, df2017, df2016, df2015, df2014, df2013], ignore_index=True)
df = df.drop(df[df['접수년도']==2023].index)
df.head().T

                   0         1            2            3            4
접수년도            2022      2022         2022         2022         2022
자치구코드          11560     11560        11215        11620        11620
자치구명            영등포구      영등포구          광진구          관악구          관악구
법정동코드        12600.0   11800.0      10700.0      10100.0      10100.0
법정동명           양평동2가       도림동          화양동          봉천동          봉천동
지번구분코드           1.0       NaN          1.0          NaN          NaN
지번구분              대지       NaN           대지          NaN          NaN
본번               1.0       NaN        111.0          NaN          NaN
부번               3.0       NaN         12.0          NaN          NaN
층                6.0       NaN         19.0          NaN          NaN
계약일         20220101  20220101     20220101     20220101     20220101
전월세구분             전세        월세           월세           월세           전세
임대면적           18.84      20.0        27.82         18.5         14.0
보증금(만원)        16000       300        10000         4000        13000
임대료(만원)            0        30          135           40            0
건물명             힘멜하임       NaN          NaN          NaN          NaN
건축년도          2014.0    1986.0       2021.0       2019.0       2019.0
건물용도            오피스텔     단독다가구         오피스텔        단독다가구        단독다가구
계약기간     22.01~24.01       NaN  22.01~24.01  22.02~23.02  22.01~24.01
신규계약구분            신규       NaN           신규           신규           신규
갱신청구권사용          NaN       NaN          NaN          NaN          NaN
종전보증금            0.0       NaN          0.0          0.0          0.0
종전임대료            NaN       NaN          0.0          0.0          NaN

In [ ]:
df.shape

(4410199, 23)

In [ ]:
df.isna().sum()

접수년도             0
자치구코드            0
자치구명             0
법정동코드           10
법정동명            12
지번구분코드     1383610
지번구분       1383610
본번         1383104
부번         1383104
층          1391781
계약일              0
전월세구분            0
임대면적            19
보증금(만원)          0
임대료(만원)          0
건물명        1382965
건축년도         88486
건물용도             0
계약기간       3754576
신규계약구분     3813997
갱신청구권사용    4310158
종전보증금      3923621
종전임대료      4182766
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4410199 entries, 0 to 4416572
Data columns (total 23 columns):
 #   Column   Dtype
---  ------   -----
 0   접수년도     int64
 1   자치구코드    int64
 2   자치구명     object
 3   법정동코드    float64
 4   법정동명     object
 5   지번구분코드   float64
 6   지번구분     object
 7   본번       float64
 8   부번       float64
 9   층        float64
 10  계약일      int64
 11  전월세구분    object
 12  임대면적     float64
 13  보증금(만원)  int64
 14  임대료(만원)  int64
 15  건물명      object
 16  건축년도     float64
 17  건물용도     object
 18  계약기간     object
 19  신규계약구분   object
 20  갱신청구권사용  object
 21  종전보증금    float64
 22  종전임대료    float64
dtypes: float64(9), int64(5), object(9)
memory usage: 807.5+ MB

- int : 접수년도, 자치구코드, 법정동코드, 계약일, 보증금(만원), 임대료(만원)
- float : 지번구분코드, 본번, 부번, 층, 임대면적, 건축년도, 종전보증금, 종전임대료
- object : 자치구명, 법정동명, 지번구분, 전월세구분, 건물명, 계약기간, 신규계약구분, 갱신청구권사용

##### 데이터 확인

In [ ]:
df['자치구명'].unique()

array(['영등포구', '광진구', '관악구', '중구', '용산구', '송파구', '강북구', '동대문구', '성북구',
       '금천구', '중랑구', '강서구', '구로구', '성동구', '동작구', '서대문구', '강남구', '노원구',
       '종로구', '마포구', '강동구', '서초구', '은평구', '양천구', '도봉구'], dtype=object)

In [ ]:
df['자치구명'].value_counts()

송파구     360519
강남구     288899
강서구     283016
관악구     249050
강동구     235001
마포구     220333
서초구     214526
동작구     202341
영등포구    197872
노원구     189951
은평구     189852
광진구     188508
양천구     178884
구로구     164511
성북구     161610
중랑구     160226
동대문구    144354
성동구     143736
서대문구    117445
용산구     112230
도봉구     103663
금천구      99269
강북구      95107
중구       55124
종로구      54172
Name: 자치구명, dtype: int64

In [ ]:
df.groupby('전월세구분').mean(['보증금(만원)','임대료(만원)'])

,접수년도,자치구코드,법정동코드,지번구분코드,본번,부번,층,계약일,임대면적,보증금(만원),임대료(만원),건축년도,종전보증금,종전임대료
전월세구분,,,,,,,,,,,,,,
월세,2018.088279,11473.777901,10938.210094,1.002163,508.599545,18.882948,7.230429,2.017925e+07,46.143838,8071.970453,55.856970,2000.891291,4545.206721,14.672128
전세,2017.765748,11472.779319,10906.577584,1.001897,503.489349,21.238937,7.031712,2.017706e+07,58.635309,27597.531441,0.000897,2000.957911,18562.112187,NaN

#### 전처리

##### 건물명 전처리

In [ ]:
from pandas.core.groupby import DataFrameGroupBy
#주소, 단지명, 건축 연도, 면적, 층수가 같은 거래 건들을 같은상품에 대한 거래로 간주
grouped = df.groupby(['자치구명','법정동명','건축년도','건물용도'])
grouped

In [ ]:
# 각 그룹의 첫 번째 '건물명'을 가져옵니다.
first_building_names = grouped['건물명'].transform('first')
# '건물명' 컬럼을 첫 번째 '건물명'으로 업데이트합니다.
df['건물명'] = first_building_names
df

,접수년도,자치구코드,자치구명,법정동코드,법정동명,지번구분코드,지번구분,본번,부번,층,...,보증금(만원),임대료(만원),건물명,건축년도,건물용도,계약기간,신규계약구분,갱신청구권사용,종전보증금,종전임대료
0,2022,11560,영등포구,12600.0,양평동2가,1.0,대지,1.0,3.0,6.0,...,16000,0,힘멜하임,2014.0,오피스텔,22.01~24.01,신규,NaN,0.0,NaN
1,2022,11560,영등포구,11800.0,도림동,NaN,NaN,NaN,NaN,NaN,...,300,30,None,1986.0,단독다가구,NaN,NaN,NaN,NaN,NaN
2,2022,11215,광진구,10700.0,화양동,1.0,대지,111.0,12.0,19.0,...,10000,135,빌리브 인테라스,2021.0,오피스텔,22.01~24.01,신규,NaN,0.0,0.0
3,2022,11620,관악구,10100.0,봉천동,NaN,NaN,NaN,NaN,NaN,...,4000,40,None,2019.0,단독다가구,22.02~23.02,신규,NaN,0.0,0.0
4,2022,11620,관악구,10100.0,봉천동,NaN,NaN,NaN,NaN,NaN,...,13000,0,None,2019.0,단독다가구,22.01~24.01,신규,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4416568,2013,11320,도봉구,10500.0,쌍문동,NaN,NaN,NaN,NaN,NaN,...,8500,0,None,1973.0,단독다가구,NaN,NaN,NaN,NaN,NaN
4416569,2013,11200,성동구,11400.0,성수동1가,NaN,NaN,NaN,NaN,NaN,...,14000,0,None,1989.0,단독다가구,NaN,NaN,NaN,NaN,NaN
4416570,2013,11740,강동구,10900.0,천호동,NaN,NaN,NaN,NaN,NaN,...,10000,5,None,1981.0,단독다가구,NaN,NaN,NaN,NaN,NaN
4416571,2013,11320,도봉구,10600.0,방학동,NaN,NaN,NaN,NaN,NaN,...,12000,0,None,1992.0,단독다가구,NaN,NaN,NaN,NaN,NaN
4416572,2013,11710,송파구,10700.0,가락동,NaN,NaN,NaN,NaN,NaN,...,20000,0,None,NaN,단독다가구,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['건물명'].isna().sum()

1367498

In [ ]:
df.duplicated().sum()

27

In [ ]:
#중복치 확인
df[df.duplicated()]

,접수년도,자치구코드,자치구명,법정동코드,법정동명,지번구분코드,지번구분,본번,부번,층,...,보증금(만원),임대료(만원),건물명,건축년도,건물용도,계약기간,신규계약구분,갱신청구권사용,종전보증금,종전임대료
564043,2021,11710,송파구,10600.0,삼전동,1.0,대지,126.0,1.0,5.0,...,57000,0,(168-12),2003.0,연립다세대,NaN,NaN,NaN,NaN,NaN
599797,2021,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,21.0,...,75600,0,강동역신동아파밀리에,2015.0,아파트,22.02~24.02,갱신,○,72000.0,NaN
732604,2021,11170,용산구,11800.0,원효로4가,1.0,대지,118.0,16.0,9.0,...,25200,0,산호,1977.0,아파트,NaN,NaN,NaN,NaN,NaN
844272,2021,11710,송파구,11300.0,거여동,1.0,대지,178.0,6.0,6.0,...,22800,0,인투파크거여,2020.0,오피스텔,22.02~24.02,신규,NaN,0.0,NaN
870319,2021,11680,강남구,10400.0,청담동,1.0,대지,12.0,8.0,5.0,...,23100,0,청담동35-8도시형생활주택(유기환외1인),2012.0,연립다세대,NaN,NaN,NaN,NaN,NaN
893793,2021,11380,은평구,10600.0,대조동,1.0,대지,223.0,10.0,7.0,...,10500,0,한리옥,2004.0,오피스텔,22.04~24.04,갱신,○,10000.0,NaN
961632,2021,11230,동대문구,10200.0,용두동,NaN,NaN,NaN,NaN,NaN,...,10470,0,None,2017.0,단독다가구,NaN,NaN,NaN,NaN,NaN
1004526,2021,11710,송파구,10100.0,잠실동,NaN,NaN,NaN,NaN,NaN,...,13000,0,None,1989.0,단독다가구,22.01~24.01,갱신,NaN,7500.0,NaN
1044377,2021,11560,영등포구,11800.0,도림동,NaN,NaN,NaN,NaN,NaN,...,1000,60,None,1999.0,단독다가구,NaN,NaN,NaN,NaN,NaN
1050272,2021,11215,광진구,10300.0,구의동,NaN,NaN,NaN,NaN,NaN,...,13500,0,None,1994.0,단독다가구,NaN,NaN,NaN,NaN,NaN
1217933,2020,11440,마포구,10100.0,아현동,1.0,대지,777.0,0.0,13.0,...,75000,0,마포래미안푸르지오2단지,2014.0,아파트,NaN,NaN,NaN,NaN,NaN
1287133,2020,11680,강남구,10300.0,개포동,1.0,대지,12.0,0.0,12.0,...,33000,0,성원대치2단지아파트,1992.0,아파트,NaN,NaN,NaN,NaN,NaN
1645400,2019,11560,영등포구,10100.0,영등포동,1.0,대지,602.0,109.0,3.0,...,26500,0,국제알앤씨빌,2019.0,연립다세대,NaN,NaN,NaN,NaN,NaN
2203841,2018,11740,강동구,10600.0,둔촌동,1.0,대지,67.0,10.0,7.0,...,38500,0,서울캐슬,2018.0,연립다세대,NaN,NaN,NaN,NaN,NaN
2234053,2018,11590,동작구,10700.0,사당동,1.0,대지,105.0,0.0,3.0,...,40000,0,극동(105),1993.0,아파트,NaN,NaN,NaN,NaN,NaN
2319310,2018,11740,강동구,10700.0,암사동,1.0,대지,470.0,18.0,5.0,...,22000,0,까사팔공육,2018.0,연립다세대,NaN,NaN,NaN,NaN,NaN
2936692,2016,11350,노원구,10200.0,월계동,1.0,대지,949.0,0.0,1.0,...,32000,0,꿈의숲SKVIEW,2016.0,아파트,NaN,NaN,NaN,NaN,NaN
2936713,2016,11350,노원구,10200.0,월계동,1.0,대지,949.0,0.0,15.0,...,41000,0,꿈의숲SKVIEW,2016.0,아파트,NaN,NaN,NaN,NaN,NaN
2983707,2016,11500,강서구,10200.0,등촌동,1.0,대지,532.0,13.0,5.0,...,19500,0,719,2015.0,연립다세대,NaN,NaN,NaN,NaN,NaN
3068595,2016,11710,송파구,11100.0,방이동,1.0,대지,89.0,0.0,22.0,...,57000,0,올림픽선수기자촌1단지,1988.0,아파트,NaN,NaN,NaN,NaN,NaN
3115945,2016,11710,송파구,10800.0,문정동,1.0,대지,618.0,0.0,13.0,...,53500,0,파크하비오,2016.0,아파트,NaN,NaN,NaN,NaN,NaN
3115948,2016,11710,송파구,10800.0,문정동,1.0,대지,618.0,0.0,11.0,...,52000,0,파크하비오,2016.0,아파트,NaN,NaN,NaN,NaN,NaN
3342716,2015,11500,강서구,10400.0,가양동,1.0,대지,1459.0,0.0,9.0,...,32000,0,가양도시개발9-2단지,1993.0,아파트,NaN,NaN,NaN,NaN,NaN
3364737,2015,11440,마포구,10100.0,아현동,1.0,대지,777.0,0.0,4.0,...,5936,0,마포래미안푸르지오2단지,2014.0,아파트,NaN,NaN,NaN,NaN,NaN
3364740,2015,11440,마포구,10100.0,아현동,1.0,대지,777.0,0.0,9.0,...,5936,0,마포래미안푸르지오2단지,2014.0,아파트,NaN,NaN,NaN,NaN,NaN
3364791,2015,11440,마포구,10100.0,아현동,1.0,대지,777.0,0.0,4.0,...,5936,0,마포래미안푸르지오2단지,2014.0,아파트,NaN,NaN,NaN,NaN,NaN
3915542,2014,11290,성북구,10300.0,돈암동,1.0,대지,609.0,1.0,20.0,...,28000,0,한진(609-1),1998.0,아파트,NaN,NaN,NaN,NaN,NaN

- 중복이 왜 생겼을까?

In [ ]:
#계약일로 정렬
df_1 = df.sort_values('계약일', ascending=True)

In [ ]:
#중복값 검색
df_1[(df['건물명']=='강동역신동아파밀리에')]

<ipython-input-16-f53ee37dab92>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_1[(df['건물명']=='강동역신동아파밀리에')]

,접수년도,자치구코드,자치구명,법정동코드,법정동명,지번구분코드,지번구분,본번,부번,층,...,보증금(만원),임대료(만원),건물명,건축년도,건물용도,계약기간,신규계약구분,갱신청구권사용,종전보증금,종전임대료
3298174,2015,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,3.0,...,50000,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
3298167,2015,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,7.0,...,53000,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
3298175,2015,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,19.0,...,56000,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
3298168,2015,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,33.0,...,56000,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
3298176,2015,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,2.0,...,50000,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465770,2022,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,34.0,...,20000,214,강동역신동아파밀리에,2015.0,아파트,23.01~25.01,갱신,○,20000.0,200.0
469867,2022,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,5.0,...,83000,0,강동역신동아파밀리에,2015.0,아파트,23.01~25.01,신규,NaN,0.0,NaN
549815,2022,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,37.0,...,73500,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
549817,2022,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,41.0,...,95000,0,강동역신동아파밀리에,2015.0,아파트,NaN,NaN,NaN,NaN,NaN
549819,2022,11740,강동구,10900.0,천호동,1.0,대지,447.0,17.0,41.0,...,95000,0,강동역신동아파밀리에,2015.0,아파트,22.12~24.12,갱신,NaN,90000.0,NaN

In [ ]:
#중복값 지우기!!
df = df.drop_duplicates(keep='first', ignore_index=True)
df.shape

(4410172, 23)

- 주소는 시, 군, 구, 동 단위까지 사용

##### 논문 기반 전처리

In [ ]:
#연립다세대, 단독다가구 제외 -> 아파트, 오피스텔만 남음
df = df.drop(df[(df['건물용도'] == '연립다세대') | (df['건물용도'] == '단독다가구')].index)
df = df.reset_index()

In [ ]:
df.shape

(2108525, 24)

In [ ]:
#면적 1의 자리로 반올림
df['임대면적'] = round(df['임대면적'],0)

In [ ]:
#층수는 저층의 가격이 상대적으로 낮다는 점을 고려하여 2층 이하/ 초과로 나누기
#2층 초과 -> 모두 3으로 변환
df.loc[df['층'] > 2, '층'] = 3
# -4 ~ -1층 -> 지하층(-1)으로 변환
df.loc[df['층'] < 0, '층'] = -1

논문에서 제시한 본 연구의 한계점 : 조망이나 2층 이상의 층수별 가격차이 등은 무시되었다.

In [ ]:
df['층'].value_counts()

 3.0    1871243
 2.0     141427
 1.0      95597
-1.0        239
Name: 층, dtype: int64

In [ ]:
#22.01~24.01 표기된 계약기간을 개월수로 변경
df[['시작날짜', '종료날짜']] = df['계약기간'].str.split('~', expand=True)
df['시작날짜'] = df['시작날짜'].astype(str).apply(lambda x: '20' + x if len(x) == 5 else x)
df['종료날짜'] = df['종료날짜'].astype(str).apply(lambda x: '20' + x if len(x) == 5 else x)
df['시작날짜'] = df['시작날짜'].replace({'None':np.nan})
df['종료날짜'] = df['종료날짜'].replace({'None':np.nan})
df['계약기간(개월)'] = (pd.to_datetime(df['종료날짜'], format='%Y.%m') - pd.to_datetime(df['시작날짜'], format='%Y.%m')).dt.days // 30

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,2108515,2108516,2108517,2108518,2108519,2108520,2108521,2108522,2108523,2108524
index,0,2,74,76,78,80,84,92,94,96,...,4295138,4295139,4295142,4295143,4295146,4295150,4295167,4295175,4295176,4295177
접수년도,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,...,2013,2013,2013,2013,2013,2013,2013,2013,2013,2013
자치구코드,11560,11215,11440,11680,11440,11740,11170,11620,11620,11740,...,11740,11740,11380,11380,11380,11170,11650,11230,11230,11230
자치구명,영등포구,광진구,마포구,강남구,마포구,강동구,용산구,관악구,관악구,강동구,...,강동구,강동구,은평구,은평구,은평구,용산구,서초구,동대문구,동대문구,동대문구
법정동코드,12600.0,10700.0,10200.0,10100.0,12500.0,10200.0,12900.0,10100.0,10100.0,10200.0,...,10900.0,10900.0,10400.0,10400.0,10500.0,10100.0,10200.0,10600.0,10600.0,10600.0
법정동명,양평동2가,화양동,공덕동,역삼동,성산동,고덕동,이촌동,봉천동,봉천동,고덕동,...,천호동,천호동,갈현동,갈현동,구산동,후암동,양재동,장안동,장안동,장안동
지번구분코드,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
지번구분,대지,대지,대지,대지,대지,대지,대지,대지,대지,대지,...,대지,대지,대지,대지,대지,대지,대지,대지,대지,대지
본번,1.0,111.0,43.0,825.0,50.0,693.0,402.0,869.0,1712.0,693.0,...,449.0,449.0,327.0,327.0,3.0,244.0,378.0,418.0,418.0,418.0
부번,3.0,12.0,0.0,20.0,10.0,0.0,0.0,10.0,0.0,0.0,...,49.0,49.0,15.0,15.0,24.0,91.0,1.0,3.0,3.0,3.0
층,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,...,3.0,3.0,2.0,1.0,3.0,3.0,1.0,3.0,3.0,3.0
계약일,20220101,20220101,20220101,20220101,20220101,20220101,20220101,20220101,20220101,20220101,...,20131110,20121218,20130207,20130302,20130326,20130913,20131104,20130304,20130313,20130802
전월세구분,전세,월세,월세,전세,월세,전세,전세,전세,전세,전세,...,월세,전세,전세,전세,전세,전세,전세,월세,월세,월세
임대면적,19.0,28.0,60.0,25.0,26.0,60.0,59.0,24.0,60.0,74.0,...,20.0,29.0,69.0,69.0,42.0,82.0,164.0,23.0,23.0,23.0
보증금(만원),16000,10000,0,29500,1000,36000,65000,18000,37800,85000,...,500,7000,16000,15000,12500,27000,57000,1500,1500,3000
임대료(만원),0,135,100,0,45,0,0,0,0,0,...,40,0,0,0,0,0,0,50,50,40
건물명,힘멜하임,빌리브 인테라스,공덕2삼성래미안,강남역 센트럴 푸르지오 시티,골든빌오피스텔(50-10),고덕그라시움,강촌,관악센츄리타워,관악드림(동아),고덕그라시움,...,힐탑프라자,힐탑프라자,반도하우드,반도하우드,힐튼렉스빌,후암,힐하우스,SM타워 오피스텔,SM타워 오피스텔,SM타워 오피스텔
건축년도,2014.0,2021.0,2004.0,2015.0,2003.0,2019.0,1998.0,1995.0,2003.0,2019.0,...,1994.0,1994.0,2007.0,2007.0,2011.0,2002.0,1998.0,2012.0,2012.0,2012.0
건물용도,오피스텔,오피스텔,아파트,오피스텔,오피스텔,아파트,아파트,오피스텔,아파트,아파트,...,오피스텔,오피스텔,아파트,아파트,오피스텔,아파트,아파트,오피스텔,오피스텔,오피스텔
계약기간,22.01~24.01,22.01~24.01,22.01~23.12,22.01~23.01,22.01~23.12,NaN,22.03~24.03,22.01~24.01,22.01~24.01,22.02~24.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
신규계약구분,신규,신규,신규,신규,신규,NaN,신규,신규,신규,신규,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
갱신청구권사용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
종전보증금,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
종전임대료,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
시작날짜,2022.01,2022.01,2022.01,2022.01,2022.01,nan,2022.03,2022.01,2022.01,2022.02,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
종료날짜,2024.01,2024.01,2023.12,2023.01,2023.12,nan,2024.03,2024.01,2024.01,2024.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
계약기간(개월),24.0,24.0,23.0,12.0,23.0,NaN,24.0,24.0,24.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(2108525, 27)

- 전월세 전환율 데이터

In [ ]:
#2011년~2022년 서울 전월세전환율 데이터
conversion = pd.read_csv('/content/drive/MyDrive/project2/전월세전환율_2011_2022.csv', encoding='cp949')

In [ ]:
date = pd.to_datetime(df['계약일'], format='%Y%m%d')
df['계약년월'] = date.dt.strftime('%Y.%m') #전월세전환율 데이터와 합치는데 필요

- 오피스텔의 주택유형 : 아파트, 연립다세대, 단독주택 중 **아파트와 가장 유사하다고 생각** -> 아파트 전월세전환율 사용

In [ ]:
#각 레코드 계약월에 해당하는 전월세전환율(아파트) 저장
mask = df['계약년월'].isin(conversion.columns)
df.loc[mask, '전월세전환율'] = conversion.loc[1, df.loc[mask, '계약년월']].values
df['전월세전환율'] = df['전월세전환율'].fillna(0)

In [ ]:
df['전월세전환율'].isna().sum()

0

- 보증금이 3년치 월세를 초과하는 *보증부월세*의 경우 월별, (지역별, 면적별) 전월세전환율을 이용하여 전세로 환산
  - df.loc[(df['전월세구분']=='월세') & (df['계약기간'] >= 36.0) & (df['계약기간']*df['임대료(만원)'] > df['보증금(만원)'])]
  - 논문 기반 전처리에 존재하는 내용 -> *모두 월세로 분류됨* -> **생략!**
  - #df.loc[~((df['전월세구분'] == '월세') & (df['계약기간(개월)'] >= 36.0) & (df['계약기간(개월)'] * df['임대료(만원)'] <= df['보증금(만원)'])), '전월세구분'] = '월세'

- 전세 -> 월세 공식으로 바꿔보면
- 전세보증금 = 월세 * 계약기간(개월) / 전환율 + 월세보증금
- https://yellowsugar.tistory.com/69

In [ ]:
mask1 = ((df['전월세구분'] == '월세') & (df['계약기간(개월)'] >= 36.0) & (df['계약기간(개월)'] * df['임대료(만원)'] <= df['보증금(만원)']))
df.loc[mask1, '전월세구분'] = '전월세 전환'
df.loc[mask1, '보증금(만원)'] = df.loc[mask1, '임대료(만원)'] * df.loc[mask1, '계약기간(개월)'] / df.loc[mask1, '전월세전환율'] + df.loc[mask1, '보증금(만원)']
df.loc[mask1,'임대료(만원)'] = 0

In [ ]:
df['전월세구분'].value_counts()

전세        1348635
월세         759438
전월세 전환        452
Name: 전월세구분, dtype: int64

- 보증금(만원)이 3,400만원 이하인 경우도 월세에 가깝다고 봐서 월세로 판단

In [ ]:
df.loc[df['보증금(만원)'] <= 3400 , '전월세구분'] = '월세'

##### 전처리

In [ ]:
df['전월세구분'].value_counts()

전세        1345932
월세         762145
전월세 전환        448
Name: 전월세구분, dtype: int64

- 역전세 위험이 있는 전세데이터를 활용하기로 결정
- 월세의 경우 역전세 리스크가 적을 것으로 판단되어 논문기반 조건에 만족하는 월세는 전세로 변환하여 활용
  - 전세가율 계산의 정확도를 올리기 위해

In [ ]:
df = df[df['전월세구분']!='월세']

In [ ]:
df.shape

(1346380, 29)

- **반전세** = 보증부월세주택
  - 전월세구분 == 전세 & 임대료(만원) != 0 인 레코드가 83개 존재함
  - 제거

In [ ]:
df = df.drop(df[(df['전월세구분'] == '전세') & (df['임대료(만원)'] != 0)].index)
df = df.reset_index()
df.shape

(1346297, 30)

In [ ]:
df['전월세구분'].value_counts()

전세        1345849
전월세 전환        448
Name: 전월세구분, dtype: int64

- 계약기간(개월) 결측치 처리
  - 아파트 전세 /오피스텔 전세 : 24개월

In [ ]:
#아파트
df[(df['건물용도']=='아파트')]['계약기간(개월)'].describe()

count    160252.000000
mean         23.646157
std           3.687016
min           0.000000
25%          24.000000
50%          24.000000
75%          24.000000
max         116.000000
Name: 계약기간(개월), dtype: float64

In [ ]:
df[df['건물용도']=='아파트']['계약기간(개월)'].value_counts()
# 145359 / 160252 = 90.7%가 24개월

24.0    145359
12.0      3451
23.0      2450
25.0       855
48.0       715
         ...
64.0         1
78.0         1
57.0         1
88.0         1
70.0         1
Name: 계약기간(개월), Length: 72, dtype: int64

In [ ]:
# 오피스텔
df[(df['건물용도']=='오피스텔')]['계약기간(개월)'].describe()

count    33455.000000
mean        22.014378
std          4.659924
min          1.000000
25%         24.000000
50%         24.000000
75%         24.000000
max         85.000000
Name: 계약기간(개월), dtype: float64

In [ ]:
df[df['건물용도']=='오피스텔']['계약기간(개월)'].value_counts()
# 27141 / 33530 = 80.9%가 24개월

24.0    27100
12.0     5064
23.0      548
11.0       88
13.0       60
25.0       52
18.0       50
14.0       43
6.0        36
15.0       33
26.0       30
36.0       28
17.0       27
16.0       23
3.0        23
19.0       23
20.0       22
2.0        21
22.0       20
7.0        20
10.0       17
21.0       15
9.0        14
27.0       13
48.0       12
30.0       11
8.0        11
4.0         9
5.0         9
1.0         6
28.0        6
29.0        5
35.0        3
31.0        2
76.0        2
62.0        1
60.0        1
83.0        1
84.0        1
72.0        1
74.0        1
47.0        1
85.0        1
33.0        1
Name: 계약기간(개월), dtype: int64

In [ ]:
#계약기간(개월) 결측치 24개월로 처리
df.loc[(df['건물용도'] == '아파트') & (df['전월세구분'] == '전세') & df['계약기간(개월)'].isna(), '계약기간(개월)'] = 24
df.loc[(df['건물용도'] == '오피스텔') & (df['전월세구분'] == '전세') & df['계약기간(개월)'].isna(), '계약기간(개월)'] = 24

In [ ]:
df['계약기간(개월)'].isna().sum()

0

In [ ]:
df['전월세구분'].value_counts()

전세        1345849
전월세 전환        448
Name: 전월세구분, dtype: int64

In [ ]:
df.shape

(1346297, 30)

##### column 정리

**개념**
- 종전보증금, 종전임대료
  - 전세가가 내려가면 같이 내려감
  - **갱신**할 때 당시 시세에 영향을 받음
- 갱신청구권
  - 임차인이 한 번 더 계약할 수 있는 권리

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1346297 entries, 0 to 1346296
Data columns (total 30 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   level_0   1346297 non-null  int64
 1   index     1346297 non-null  int64
 2   접수년도      1346297 non-null  int64
 3   자치구코드     1346297 non-null  int64
 4   자치구명      1346297 non-null  object
 5   법정동코드     1346295 non-null  float64
 6   법정동명      1346294 non-null  object
 7   지번구분코드    1346108 non-null  float64
 8   지번구분      1346108 non-null  object
 9   본번        1346108 non-null  float64
 10  부번        1346108 non-null  float64
 11  층         1346287 non-null  float64
 12  계약일       1346297 non-null  int64
 13  전월세구분     1346297 non-null  object
 14  임대면적      1346287 non-null  float64
 15  보증금(만원)   1346297 non-null  float64
 16  임대료(만원)   1346297 non-null  int64
 17  건물명       1340591 non-null  object
 18  건축년도      1340594 non-null  float64
 19  건물용도      1346297 non-null  object
 20  계약기간      193707 non-null   object
 21  신규계약구분    182299 non-null   object
 22  갱신청구권사용   57317 non-null    object
 23  종전보증금     154262 non-null   float64
 24  종전임대료     230 non-null      float64
 25  시작날짜      1346297 non-null  object
 26  종료날짜      315909 non-null   object
 27  계약기간(개월)  1346297 non-null  float64
 28  계약년월      1346297 non-null  object
 29  전월세전환율    1346297 non-null  float64
dtypes: float64(12), int64(6), object(12)
memory usage: 308.1+ MB

In [ ]:
df.columns

Index(['level_0', 'index', '접수년도', '자치구코드', '자치구명', '법정동코드', '법정동명', '지번구분코드',
       '지번구분', '본번', '부번', '층', '계약일', '전월세구분', '임대면적', '보증금(만원)', '임대료(만원)',
       '건물명', '건축년도', '건물용도', '계약기간', '신규계약구분', '갱신청구권사용', '종전보증금', '종전임대료',
       '시작날짜', '종료날짜', '계약기간(개월)', '계약년월', '전월세전환율'],
      dtype='object')

In [ ]:
df['전월세구분'].value_counts()

전세        1345849
전월세 전환        448
Name: 전월세구분, dtype: int64

- 제거할 column
  - 접수년도, 시작날짜, 종료날짜, 갱신청구권사용
  - 자치구코드, 법정동코드, 지번구분코드, 지번구분
  - 임대료(만원), 계약기간
  - drop_duplicate

In [ ]:
df = df.drop(['level_0', 'index', '시작날짜', '종료날짜','갱신청구권사용'], axis=1)
df = df.drop(['자치구코드', '법정동코드', '지번구분코드', '지번구분'], axis=1)
df = df.drop(['임대료(만원)', '계약기간'], axis=1)
df = df.drop('전월세전환율', axis=1)
df = df.drop_duplicates(ignore_index=True)
df.shape

(1321126, 18)

In [ ]:
# 2013년도 이전 데이터 제거
df = df.drop(df[df['계약일'] < 20130000].index)
df.shape

(1305038, 18)

In [ ]:
df.head().T

                 0                1         2         3         4
접수년도          2022             2022      2022      2022      2022
자치구명          영등포구              강남구       강동구       용산구       관악구
법정동명         양평동2가              역삼동       고덕동       이촌동       봉천동
본번             1.0            825.0     693.0     402.0     869.0
부번             3.0             20.0       0.0       0.0      10.0
층              3.0              3.0       2.0       3.0       3.0
계약일       20220101         20220101  20220101  20220101  20220101
전월세구분           전세               전세        전세        전세        전세
임대면적          19.0             25.0      60.0      59.0      24.0
보증금(만원)    16000.0          29500.0   36000.0   65000.0   18000.0
건물명           힘멜하임  강남역 센트럴 푸르지오 시티    고덕그라시움        강촌   관악센츄리타워
건축년도        2014.0           2015.0    2019.0    1998.0    1995.0
건물용도          오피스텔             오피스텔       아파트       아파트      오피스텔
신규계약구분          신규               신규       NaN        신규        신규
종전보증금          0.0              0.0       NaN       0.0       0.0
종전임대료          NaN              NaN       NaN       NaN       NaN
계약기간(개월)      24.0             12.0      24.0      24.0      24.0
계약년월       2022.01          2022.01   2022.01   2022.01   2022.01

#### 신축여부, 면적구분 column 생성

##### 계약일 int -> datetime으로 변경

In [ ]:
df['계약일'] = df['계약일'].apply(lambda x: pd.to_datetime(str(x), format='%Y-%m-%d' ))
df['계약년월'] = df['계약일'].dt.strftime('%Y.%m')
df['계약년도'] = df['계약일'].dt.year
df['계약월'] = df['계약일'].dt.month
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1305038 entries, 0 to 1321125
Data columns (total 20 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   접수년도      1305038 non-null  int64
 1   자치구명      1305038 non-null  object
 2   법정동명      1305035 non-null  object
 3   본번        1304850 non-null  float64
 4   부번        1304850 non-null  float64
 5   층         1305028 non-null  float64
 6   계약일       1305038 non-null  datetime64[ns]
 7   전월세구분     1305038 non-null  object
 8   임대면적      1305028 non-null  float64
 9   보증금(만원)   1305038 non-null  float64
 10  건물명       1299402 non-null  object
 11  건축년도      1299405 non-null  float64
 12  건물용도      1305038 non-null  object
 13  신규계약구분    178546 non-null   object
 14  종전보증금     151268 non-null   float64
 15  종전임대료     230 non-null      float64
 16  계약기간(개월)  1305038 non-null  float64
 17  계약년월      1305038 non-null  object
 18  계약년도      1305038 non-null  int64
 19  계약월       1305038 non-null  int64
dtypes: datetime64[ns](1), float64(9), int64(3), object(7)
memory usage: 209.1+ MB

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,1321115,1321116,1321117,1321118,1321119,1321121,1321122,1321123,1321124,1321125
접수년도,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,...,2013,2013,2013,2013,2013,2013,2013,2013,2013,2013
자치구명,영등포구,강남구,강동구,용산구,관악구,관악구,강동구,동작구,성북구,동작구,...,강동구,강동구,강동구,강동구,강동구,은평구,은평구,은평구,용산구,서초구
법정동명,양평동2가,역삼동,고덕동,이촌동,봉천동,봉천동,고덕동,동작동,돈암동,동작동,...,천호동,천호동,천호동,천호동,천호동,갈현동,갈현동,구산동,후암동,양재동
본번,1.0,825.0,693.0,402.0,869.0,1712.0,693.0,102.0,636.0,102.0,...,449.0,449.0,449.0,449.0,449.0,327.0,327.0,3.0,244.0,378.0
부번,3.0,20.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,...,49.0,49.0,49.0,49.0,49.0,15.0,15.0,24.0,91.0,1.0
층,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,2.0,1.0,3.0,3.0,1.0
계약일,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,2022-01-01 00:00:00,...,2013-05-13 00:00:00,2013-06-27 00:00:00,2013-07-06 00:00:00,2013-07-13 00:00:00,2013-08-31 00:00:00,2013-02-07 00:00:00,2013-03-02 00:00:00,2013-03-26 00:00:00,2013-09-13 00:00:00,2013-11-04 00:00:00
전월세구분,전세,전세,전세,전세,전세,전세,전세,전세,전세,전세,...,전세,전세,전세,전세,전세,전세,전세,전세,전세,전세
임대면적,19.0,25.0,60.0,59.0,24.0,60.0,74.0,60.0,60.0,60.0,...,20.0,20.0,20.0,20.0,20.0,69.0,69.0,42.0,82.0,164.0
보증금(만원),16000.0,29500.0,36000.0,65000.0,18000.0,37800.0,85000.0,94000.0,53000.0,94000.0,...,5000.0,4000.0,6000.0,5500.0,5000.0,16000.0,15000.0,12500.0,27000.0,57000.0
건물명,힘멜하임,강남역 센트럴 푸르지오 시티,고덕그라시움,강촌,관악센츄리타워,관악드림(동아),고덕그라시움,이수스위첸포레힐즈,이수브라운스톤돈암,이수스위첸포레힐즈,...,힐탑프라자,힐탑프라자,힐탑프라자,힐탑프라자,힐탑프라자,반도하우드,반도하우드,힐튼렉스빌,후암,힐하우스
건축년도,2014.0,2015.0,2019.0,1998.0,1995.0,2003.0,2019.0,2022.0,2004.0,2022.0,...,1994.0,1994.0,1994.0,1994.0,1994.0,2007.0,2007.0,2011.0,2002.0,1998.0
건물용도,오피스텔,오피스텔,아파트,아파트,오피스텔,아파트,아파트,아파트,아파트,아파트,...,오피스텔,오피스텔,오피스텔,오피스텔,오피스텔,아파트,아파트,오피스텔,아파트,아파트
신규계약구분,신규,신규,NaN,신규,신규,신규,신규,신규,신규,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
종전보증금,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
종전임대료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
계약기간(개월),24.0,12.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,...,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0
계약년월,2022.01,2022.01,2022.01,2022.01,2022.01,2022.01,2022.01,2022.01,2022.01,2022.01,...,2013.05,2013.06,2013.07,2013.07,2013.08,2013.02,2013.03,2013.03,2013.09,2013.11
계약년도,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,...,2013,2013,2013,2013,2013,2013,2013,2013,2013,2013
계약월,1,1,1,1,1,1,1,1,1,1,...,5,6,7,7,8,2,3,3,9,11

##### 신축여부 (EDA:건물용도별 건축년도별 전세보증금)
- ~ 5년 : 신축
- 6 ~ 10년 : 준신축
- 11년 ~ : 구축

In [ ]:
df['건축년도'].isna().sum()

5633

In [ ]:
# 신축여부 컬럼 생성
df['신축여부'] = " "
df.loc[(df['계약년도'] - df['건축년도']) <= 5, '신축여부'] = "신축"
df.loc[((df['계약년도'] - df['건축년도']) > 5) & ((df['계약년도'] - df['건축년도']) <= 10), '신축여부'] = "준신축"
df.loc[(df['계약년도'] - df['건축년도']) > 10, '신축여부'] = "구축"

In [ ]:
df['신축여부'].value_counts()

구축     862163
신축     257628
준신축    179614
         5633
Name: 신축여부, dtype: int64

##### 면적구분 (EDA:건물용도별 임대면적별 전세보증금)
- 59㎡ 미만 / 59㎡ 이상 84㎡ 이하 / 84㎡ 초과

In [ ]:
df['임대면적'].describe()

count    1.305028e+06
mean     7.122731e+01
std      3.103890e+01
min      8.000000e+00
25%      5.200000e+01
50%      7.100000e+01
75%      8.500000e+01
max      4.450000e+02
Name: 임대면적, dtype: float64

In [ ]:
df['임대면적'].isna().sum()

10

In [ ]:
df.loc[df['임대면적'] < 59, '면적구분'] = "59㎡ 미만"
df.loc[(df['임대면적'] >= 59) & (df['임대면적'] <= 84), '면적구분'] = "59㎡ 이상 84㎡ 이하"
df.loc[df['임대면적'] > 84, '면적구분'] = "84㎡ 초과"

In [ ]:
df['면적구분'].value_counts()

84㎡ 초과           517139
59㎡ 이상 84㎡ 이하    414802
59㎡ 미만           373087
Name: 면적구분, dtype: int64

### 데이터 저장

In [ ]:
df.to_csv('complete_2.csv',index=False)